= Accounts

[[Intro]]
== Intro
This project was born with the aim of providing a sample microservice application with TDD.

 * This microservice will store client accounts in a mysql DB and have
 swagger as API Interface.

== API overview
* POST invocation (body example) to /accounts:
[source,json]
----
{
    "accountId": "010340430A",
    "alias": "yourself",
    "amount": 123,
    "number": "pepe",
    "currency":"CAD",
    "type":"outgoings"
  }
----
* GET invocation ( Response body example) to /accounts/010340430A:
[source,json]
----
{
    "accountId": "010340430A",
    "alias": "yourself",
    "amount": 123,
    "number": "pepe",
    "currency":"CAD",
    "type":"outgoings"
  }
----



== Motivation
**Account** application is intended to demonstrate the basics concepts of a microservices architecture.

== Build this microservice
Build project
----
gradle clean install
----
== Run on local environment

----
gradle bootRun
----

----
java -jar account.jar
----


== Importing the project into eclipse

On build.gradle file, add an eclipse task:
----
apply plugin: 'eclipse'
----

And then, on command line/terminal:
----
gradle eclipse
----

Finally, install link:http://marketplace.eclipse.org/content/buildship-gradle-integration[Buildship Gradle Integration 2.0] plugin for Eclipse

[[Structure]]
= Project Structure and Dependencies

[[Java8]]
== Java 8

link:http://www.oracle.com/technetwork/articles/java/java8-optional-2175753.html[Tired of Null Pointer Exceptions? Consider Using Java SE 8's Optional!]

link:http://blog.algaworks.com/chega-de-nullpointerexception/[PT-BR: Chega de NullPointerException! Use a classe Optional]

[[Lombok]]
== Lombok

link:https://projectlombok.org/[Lombok] just makes your life easier providing annotations to increase your productivity. 
E.g.: Generate all getters, setters, toString, hashCode and equals methods by just adding a @Data annotation. 
Please watch de demo video, read the documentation and let's think about how much time our lives were wasted doing everything lombok provides.

[[TDD]]
== TDD
**Account** fowllows **TDD** practices for both unit and integration tests.

Useful Links:

link:https://www.casadocodigo.com.br/products/livro-tdd[Book - TDD with Java (Brazillian Portuguese)]

link:https://objectpartners.com/2013/09/18/the-benefits-of-using-assertthat-over-other-assert-methods-in-unit-tests/#comment-55827[Why you should use assertThat instead of other Methods in JUnit]

link:http://site.mockito.org/[Mockito] - Hint: Cool developers use mockito methods through static imports
